"""Standard sector to industry mapping used for classification validation."""

STANDARD_SECTORS = {
    "Agriculture": [
        "Agricultural Machinery Manufacturing",
        "Agricultural Production",
        "Agricultural Technology",
        "Agriculture and Food Technology",
        "Animal Breeding & Production",
        "Animal Husbandry",
        "Animal Production & Distribution",
        "Biochemical Manufacturing",
        "Corn Processing",
        "Seed Production",
        "Tobacco Production",
    ],
    "Automotive": [
        "Automotive Engineering and Manufacturing",
        "Electric Motorcycle Manufacturing",
    ],
    "Communication Services": [
        "Animation & Culture Services",
        "Cable Television Services",
        "Digital Asset Management",
        "Digital Entertainment Services",
        "Film Production & Distribution",
        "In-flight Connectivity Services",
        "Internet Software Development",
        "Internet Technology Services",
        "Media & Digital Services",
        "Media & Entertainment",
        "Media and Entertainment",
        "Online Communication Services",
        "Online Community Services",
        "Online Dating Services",
        "Online Freelance Services",
        "Online Gaming Services",
        "Online Review Services",
        "Satellite Communication Services",
        "Satellite Technology Services",
        "Social Media Management",
        "Telecommunications Services",
        "Telecommunications Technology",
        "Television Broadcasting",
        "Weather Information Services",
        "Wireless Communication Technology",
    ],
    "Consulting Services": [
        "Consulting Services",
    ],
    "Consumer Discretionary": [
        "Aircraft Leasing Services",
        "Apparel & Accessories",
        "Automotive Retail",
        "Automotive Services",
        "Automotive Technology",
        "Beauty & Personal Care",
        "Bicycles Manufacturing",
        "Consumer Electronics Manufacturing",
        "Consumer Electronics Retail",
        "Consumer Products Manufacturing",
        "Consumer Services",
        "Convenience Store Operations",
        "Crafting Technology",
        "Creative Design Services",
        "Cultural Development Services",
        "Dental Products & Services",
        "Department Store Retail",
        "Department Stores",
        "Digital Coupon Services",
        "E-commerce Services",
        "Eco-Friendly Products",
        "Education Services",
        "Educational Technology Services",
        "Electric Bicycle Manufacturing",
        "Electric Vehicle Manufacturing",
        "Entertainment",
        "Entertainment Services",
        "Entrepreneurial Services",
        "Exhibition Services",
        "Fast Food Restaurants",
        "Fishing Equipment Manufacturing",
        "Footwear Manufacturing",
        "Footwear Retail",
        "Furniture & Home Furnishings",
        "Gaming & Entertainment",
        "Gaming Hardware Manufacturing",
        "Gaming Services",
        "Gift Retail Services",
        "Health & Fitness",
        "Home Goods Retail",
        "Home Services",
        "Home Services Technology",
        "Horse Racing Services",
        "Hotels & Hospitality",
        "Household Appliances Manufacturing",
        "Household Products",
        "Housewares Manufacturing",
        "Jewelry Manufacturing",
        "Jewelry Retail",
        "Kitchen Equipment Manufacturing",
        "Lottery Services",
        "Luxury Experience Services",
        "Luxury Goods Retail",
        "Luxury Yachts Manufacturing",
        "Marine Products Manufacturing",
        "Marine Products Retail",
        "Maternity & Baby Products",
        "Motorcycle Manufacturing",
        "Musical Instruments Manufacturing",
        "Online Auction Services",
        "Online Luxury Retail Services",
        "Online Personal Styling Services",
        "Online Retail Services",
        "Optical Retail Services",
        "Outdoor Equipment Manufacturing",
        "Pet Products Manufacturing",
        "Pet Products Retail",
        "Playing Cards Manufacturing",
        "Power Tools Manufacturing",
        "Publishing Services",
        "Recreation & Leisure",
        "Recreational Vehicle Manufacturing",
        "Recreational Vehicles",
        "Restaurants",
        "Retail Services",
        "Specialty Retail",
        "Sports Entertainment Services",
        "Sports Equipment Manufacturing",
        "Sun-Shading Products Manufacturing",
        "Swimming Pool Manufacturing",
        "Thrift Store Retail",
        "Toys & Games Manufacturing",
        "Toys & Games Retail",
        "Trading & Distribution",
        "Transportation Services",
        "Travel & Tourism",
        "Travel & Tourism Services",
        "Travel Accessories Manufacturing",
        "Watches & Accessories",
    ],
    "Consumer Staples": [
        "Animal Nutrition Technology",
        "Baby Food Products",
        "Baked Goods Manufacturing",
        "Beverages",
        "Cannabis Production",
        "Cereal Production",
        "Coffee Products",
        "Condiment Manufacturing",
        "Confectionery Manufacturing",
        "Consumer Health & Wellness",
        "Dairy Products",
        "Fish Production & Distribution",
        "Flavor & Fragrance Manufacturing",
        "Flour Milling",
        "Food & Drug Retail",
        "Food Production",
        "Food Products",
        "Fruit Production & Distribution",
        "Grain and Oil Production",
        "Grocery Retail",
        "Grocery Store Operations",
        "Health & Wellness Products",
        "Health Food Products",
        "Household Products & Personal Care",
        "Natural Ingredients Production",
        "Nut and Snack Food Production",
        "Office Supplies & Retail",
        "Office Supplies Manufacturing",
        "Snack Food Manufacturing",
        "Sugar Production & Distribution",
        "Tea Production & Distribution",
        "Tobacco & Related Products",
        "Tobacco Products",
        "Traditional Chinese Medicine",
        "Writing Instruments Manufacturing",
    ],
    "Energy": [
        "Advanced Manufacturing",
        "Clean Energy Solutions",
        "Electric Vehicle Charging Solutions",
        "Energy Conservation Services",
        "Energy Development Services",
        "Energy Investment & Development",
        "Energy Investment Fund",
        "Energy Investment Services",
        "Energy Storage Technology",
        "Energy Technology Services",
        "Fuel Services",
        "Heat Transfer Technology",
        "Hydrogen Fuel Technology",
        "Liquefied Natural Gas Shipping",
        "Marine Energy Technology",
        "Natural Gas Services",
        "Natural Gas Solutions",
        "Natural Gas Technology",
        "Natural Resource Management",
        "Nuclear Energy Services",
        "Oil & Gas Acquisition",
        "Oil & Gas Exploration",
        "Oil & Gas Refining",
        "Oil & Gas Services",
        "Petrochemical Manufacturing",
        "Renewable Energy",
        "Renewable Energy Equipment Manufacturing",
        "Renewable Energy Services",
        "Renewable Energy Technology",
        "Renewable Power Generation",
        "Solar Energy Manufacturing",
        "Solar Energy Solutions",
        "Wind Power Generation",
    ],
    "Financials": [
        "Banks",
        "Business Development Companies",
        "Exchange Traded Funds",
        "Financial Services",
        "Financial Technology Services",
        "Insurance",
        "Insurance Services",
        "Insurance Technology",
        "Insurance Technology Services",
        "Investment Holdings",
        "Investment Management Services",
        "Investment Technology Services",
        "Investment Trusts",
        "Mortgage Banking Services",
        "Mortgage Lending Services",
    ],
    "Healthcare": [
        "Animal Health Products",
        "Biotechnology & Pharmaceuticals",
        "Cannabis Products",
        "Complementary and Alternative Health Services",
        "Cryogenic Technology Manufacturing",
        "Dental and Oral Health Services",
        "Digital Health Services",
        "Fertility Services",
        "Health Technology",
        "Health Technology Services",
        "Healthcare Services",
        "Healthcare Technology",
        "Market Research Services",
        "Medical Devices",
        "Medical Technology",
        "Mental Health Services",
        "Mental and Behavioral Health Services",
        "Neurological Health Technology",
        "Pharmaceutical Manufacturing",
        "Pharmaceutical Retail",
        "Pharmaceutical and Biotech Services",
        "Pharmaceuticals",
        "Pharmacy Services",
        "Reproductive and Sexual Health Services",
        "Telehealth Services",
        "Telehealth and Remote Care Services",
        "Veterinary and Animal Health Services",
    ],
    "Industrials": [
        "Abrasives Manufacturing",
        "Access Control Technology",
        "Aerospace & Defense",
        "Agricultural Equipment",
        "Air Quality Technology",
        "Airlines",
        "Airports & Aviation Services",
        "Architectural Design Services",
        "Automotive",
        "Automotive Components",
        "Automotive Proving Ground Services",
        "Bearings Manufacturing",
        "Bus Manufacturing",
        "Business Services",
        "Commercial Landscaping Services",
        "Commercial Printing Services",
        "Commercial Services",
        "Concrete Pumping Services",
        "Construction & Engineering",
        "Construction Services",
        "Consumer Goods",
        "Control Systems Engineering",
        "Conveying Equipment Manufacturing",
        "Crane Manufacturing",
        "Custom Products Manufacturing",
        "Dredging Services",
        "Drone Technology Services",
        "Electric Power Equipment Manufacturing",
        "Electrical Equipment",
        "Electrical Equipment Manufacturing",
        "Electronic Display Manufacturing",
        "Electronic Machinery Manufacturing",
        "Electronic Manufacturing",
        "Electronic Manufacturing Services",
        "Elevator Manufacturing",
        "Energy Engineering Services",
        "Energy Equipment Manufacturing",
        "Engineering Services",
        "Environmental Services",
        "Explosive Materials Manufacturing",
        "Fan Manufacturing",
        "Fasteners Manufacturing",
        "Firearms Manufacturing",
        "Flexible Metal Hose Manufacturing",
        "Floor Cleaning Equipment Manufacturing",
        "Flow Control Technology",
        "Fluid Equipment Manufacturing",
        "Gaming Equipment Manufacturing",
        "General Manufacturing",
        "Geophysical Services",
        "Geotechnical Engineering Services",
        "HVAC Equipment Manufacturing",
        "Heat Exchanger Manufacturing",
        "Heavy Machinery Manufacturing",
        "Human Resource Technology Services",
        "Hydraulic Equipment Manufacturing",
        "Industrial Distribution Services",
        "Industrial Equipment",
        "Industrial Equipment Manufacturing",
        "Industrial Equipment Services",
        "Industrial Heating Solutions",
        "Industrial Holdings",
        "Industrial Machinery & Equipment",
        "Industrial Manufacturing",
        "Industrial Technology Manufacturing",
        "Industrial Technology Services",
        "Infrastructure Services",
        "Intelligent Drive Systems Manufacturing",
        "Intelligent Equipment Manufacturing",
        "Intelligent Manufacturing",
        "Intelligent Meter Manufacturing",
        "International Trade Services",
        "Landscaping Services",
        "Lighting Technology Manufacturing",
        "Logistics Services",
        "Logistics Technology Services",
        "Manufactured Housing",
        "Manufacturing Services",
        "Manufacturing Solutions",
        "Material Handling Equipment Manufacturing",
        "Measurement Technology",
        "Mechanical Equipment Manufacturing",
        "Memorial Products Manufacturing",
        "Microvent Technology Manufacturing",
        "Moulds & Plastics Manufacturing",
        "Municipal Services Equipment",
        "Office Furniture Manufacturing",
        "Online Printing Services",
        "Optical Equipment Manufacturing",
        "Packaging Machinery Manufacturing",
        "Packaging Technology",
        "Pipeline Construction Services",
        "Plumbing Technology Manufacturing",
        "Port Operations Services",
        "Power Equipment Manufacturing",
        "Power Generation Equipment Manufacturing",
        "Power Supply Manufacturing",
        "Precision Components Manufacturing",
        "Precision Cutting Tools Manufacturing",
        "Precision Equipment Manufacturing",
        "Precision Machinery Manufacturing",
        "Precision Manufacturing",
        "Precision Measurement Technology",
        "Printing Equipment Manufacturing",
        "Printing Services",
        "Pumping Equipment Manufacturing",
        "Railway Manufacturing",
        "Recruitment Services",
        "Refrigeration Equipment Manufacturing",
        "Rental Services",
        "Research & Development Services",
        "Safety Equipment Manufacturing",
        "Safety Products Manufacturing",
        "Safety Technology Services",
        "Security Services",
        "Seismic Isolation Technologies",
        "Shipbuilding",
        "Shipping Services",
        "Snow Removal Equipment Manufacturing",
        "Specialized Equipment Manufacturing",
        "Specialty Vehicles Manufacturing",
        "Supply Chain Management",
        "Technical Services",
        "Telematics Technology",
        "Testing & Certification Services",
        "Textile Manufacturing",
        "Tools Manufacturing",
        "Towing Services",
        "Traffic Management Solutions",
        "Transmission Technology Manufacturing",
        "Transportation & Logistics",
        "Transportation Engineering",
        "Transportation Equipment Manufacturing",
        "Transportation Infrastructure Development",
        "Transportation Technology Services",
        "Ultrasonic Technology Manufacturing",
        "Valve Manufacturing",
        "Weighing Equipment Manufacturing",
        "Welding Technology Manufacturing",
        "Wheel Manufacturing",
        "Wind Power Equipment Manufacturing",
    ],
    "Information Technology": [
        "3D Printing Technology",
        "Advanced Manufacturing Technologies",
        "Artificial Intelligence Technology",
        "Audio Equipment Manufacturing",
        "Battery Manufacturing",
        "Blockchain Technology",
        "Client Services Technology",
        "Cloud Computing Services",
        "Cloud Storage Services",
        "Communication Software Services",
        "Communication Technology Services",
        "Computer Hardware Distribution",
        "Computer Hardware Manufacturing",
        "Computer Peripherals Manufacturing",
        "Customer Experience Management Software",
        "Cybersecurity Services",
        "Data Analytics Services",
        "Data Centre Services",
        "Data Storage Technology",
        "Database Management Software",
        "Digital Advertising Services",
        "Digital Analytics Services",
        "Digital Certificate Services",
        "Digital Communication Services",
        "Digital Knowledge Management Services",
        "Digital Marketing Services",
        "Digital Marketing and Advertising",
        "Digital Media Services",
        "Digital Operations Management",
        "Digital Security Solutions",
        "Digital Technology Services",
        "Digital Textile Printing",
        "Display Technology Manufacturing",
        "Document Management Solutions",
        "Electronic Components",
        "Electronic Systems Manufacturing",
        "Electronic Technology Manufacturing",
        "Embedded Systems Development",
        "Geospatial Information Services",
        "High Technology Development",
        "High-Tech Manufacturing",
        "Home Security Technology",
        "IT Services & Solutions",
        "Information Technology Services",
        "Intelligent Circuit Manufacturing",
        "Intelligent Control Systems",
        "Intelligent Technology Manufacturing",
        "Internet of Things Technology",
        "Irradiation Technology Services",
        "Laboratory Instruments Manufacturing",
        "Laser Equipment Manufacturing",
        "Legal Technology Services",
        "LiDAR Technology",
        "Magnetic Card Manufacturing",
        "Magnetic Materials Manufacturing",
        "Marketing Services",
        "Microcontroller Technology",
        "Microelectronics Manufacturing",
        "Middleware Software Development",
        "Mobile Technology Services",
        "Navigation Technology",
        "Network Security Solutions",
        "Network Technology Services",
        "Networking Equipment Manufacturing",
        "Online Marketing Services",
        "Online Monitoring Technology",
        "Online Technology Services",
        "Optoelectronic Technology Manufacturing",
        "Payment Solutions Technology",
        "Power Management Technology",
        "Power Technology Manufacturing",
        "Precision Technology Manufacturing",
        "Quantum Computing Technology",
        "Real-Time Communication Services",
        "Restaurant Technology Solutions",
        "Robotics & Automation",
        "Semiconductor Manufacturing",
        "Semiconductor Testing Technology",
        "Smart Access Technology",
        "Smart City Technology",
        "Smart Technology Manufacturing",
        "Smart and Intelligent Technologies",
        "Software & Services",
        "Software Development Services",
        "Space Technology Services",
        "Strategic Consulting Services",
        "Supply Chain Management Technology",
        "Technology Development Services",
        "Technology Integration Services",
        "Technology Services",
        "Telecommunications",
        "Telecommunications Equipment",
        "Travel Technology Services",
        "Video Technology Services",
        "Water Treatment Technology",
        "Wireless Technology Services",
    ],
    "Materials": [
        "Activated Carbon Manufacturing",
        "Adhesive Products Manufacturing",
        "Advanced Materials",
        "Aluminium Production",
        "Antimony Mining",
        "Artificial Leather Manufacturing",
        "Asphalt Production",
        "Biomaterials Manufacturing",
        "Building Products",
        "Building and Construction Materials",
        "Cable Manufacturing",
        "Carbon Neutral Technology",
        "Cement Production",
        "Ceramics Manufacturing",
        "Chemical Manufacturing",
        "Coal Mining",
        "Coating Technology",
        "Construction Materials Manufacturing",
        "Copper Mining",
        "Electrical Alloy Manufacturing",
        "Electronic Materials Manufacturing",
        "Energy Conservation Materials Manufacturing",
        "Environmental Technology Services",
        "Ethanol Production",
        "Fertilizer Production",
        "Fertilizers & Agricultural Chemicals",
        "Fiberglass Manufacturing",
        "Fire Protection Equipment Manufacturing",
        "Flexible Packaging Manufacturing",
        "Flooring Products Manufacturing",
        "Fluoride Materials Manufacturing",
        "Forest Products",
        "Futures Trading",
        "Gas Manufacturing",
        "Glass Manufacturing",
        "Gold Mining",
        "Graphite Production",
        "Grass Production & Distribution",
        "Iron Ore Mining",
        "Isotope Production Technology",
        "Lead-Acid Battery Manufacturing",
        "Leather Manufacturing",
        "Lithium Mining",
        "Meat Production & Distribution",
        "Membrane Technology Manufacturing",
        "Metal Materials Manufacturing",
        "Metal Products Distribution",
        "Metals & Mining",
        "Mining & Exploration",
        "Molybdenum Mining & Production",
        "Moulding Materials Manufacturing",
        "Natural Resource Exploration",
        "Nickel Mining",
        "Nonwovens Manufacturing",
        "Nylon Manufacturing",
        "Packaging Materials",
        "Paper Manufacturing",
        "Petroleum Equipment Manufacturing",
        "Plastic Products Manufacturing",
        "Platinum Mining",
        "Precious Metals Manufacturing",
        "Precision Metal Manufacturing",
        "Printing Ink Manufacturing",
        "Protein Technology Manufacturing",
        "Rare Earth Mining",
        "Recycling Services",
        "Rubber Manufacturing",
        "Salt Production",
        "Sealing Technology Manufacturing",
        "Silicon Materials Manufacturing",
        "Silicone Materials Manufacturing",
        "Specialty Chemicals",
        "Specialty Minerals Manufacturing",
        "Steel & Metal Products",
        "Steel Production",
        "Stone Products Manufacturing",
        "Tantalum Production",
        "Textiles",
        "Titanium Production",
        "Tungsten Mining & Production",
        "Tyre Manufacturing",
        "Waterproofing Technology Manufacturing",
        "Wear Resistant Materials Manufacturing",
        "Welding Consumables Manufacturing",
        "Wire Rope Manufacturing",
        "Wood Plastic Composite Manufacturing",
        "Wood Products Manufacturing",
        "Zinc Production",
        "Zirconium Production",
    ],
    "Real Estate": [
        "Commercial Real Estate",
        "Funeral Services",
        "Parking Services",
        "Real Estate Brokerage Services",
        "Real Estate Consultancy",
        "Real Estate Development",
        "Real Estate Investment Trusts",
        "Real Estate Services",
        "Residential Construction",
        "Residential Home Construction",
        "Residential Real Estate",
        "Residential Real Estate Development",
        "Residential Real Estate Investment Trusts",
        "Senior Living Services",
    ],
    "Utilities": [
        "Electric Power Generation",
        "Electric Utilities",
        "Electric Utility Services",
        "Energy",
        "Energy and Utilities Services",
        "Gas Distribution",
        "Gas Utilities",
        "Hydropower Generation",
        "Natural Gas Distribution",
        "Natural Gas Utilities",
        "Power Investment & Development",
        "Water Meter Manufacturing",
        "Water Resource Management",
        "Water Treatment Services",
        "Water Utilities",
    ],
}
