# Generated by Django 5.2.6 on 2025-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_stock_analyst_target_label_stock_dividend_per_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
