# Generated by Django 5.2.5 on 2025-10-10 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_alter_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('ticker', 'exchange')},
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='screener.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='screener_hi_stock_i_bb5f7f_idx'), models.Index(fields=['date'], name='screener_hi_date_cafe19_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
