# Generated by Django 5.2.5 on 2025-10-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0005_alter_stock_ticker_alter_stock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='prices_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
