# Generated by Django 5.2.6 on 2025-10-16 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0006_stock_prices_last_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibleExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibleSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibleIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='screener.accessiblesector')),
            ],
        ),
        migrations.CreateModel(
            name='AccessibleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=200)),
                ('full_ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('operating_country', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_country_iso', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_long_name', models.CharField(blank=True, max_length=150, null=True)),
                ('exchange_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_to_book', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_to_sales', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('enterprise_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_debt_to_total_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('float_shares_to_outstanding', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('average_volume', models.BigIntegerField(blank=True, null=True)),
                ('relative_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('relative_strength_index', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prices_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('peg_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fair_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('fair_value_upside', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fair_value_label', models.CharField(blank=True, max_length=50, null=True)),
                ('analyst_target', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('analyst_upside', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('analyst_target_label', models.CharField(blank=True, max_length=100, null=True)),
                ('health_label', models.CharField(blank=True, max_length=50, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.accessibleexchange')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screener.accessibleindustry')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screener.accessiblesector')),
            ],
            options={
                'ordering': ['ticker'],
                'unique_together': {('ticker', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='AccessibleHistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='screener.accessiblestock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='screener_ac_stock_i_d2804b_idx'), models.Index(fields=['date'], name='screener_ac_date_471b1f_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
